# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks


task :deploy, :env, :remote do |t, args|
  # We don't have separate branches for production/development 
  # yet, so we comment this out
  # sh "git checkout #{args[:env]}"
  # sh 'git merge master -m "Merging for deployment"'
  sh './build.sh'

  sh 'git add -A'
  sh 'git commit -m "Compile for deployment"'
  sh 'cd ..'

  # From project root directory (not the webapp folder), 
  # this worked: sudo git subtree push --prefix=webapp heroku master
  sh "git subtree push --prefix webapp #{args[:remote]} head:master"

end